# Generated by Django 3.0.2 on 2021-01-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='languages',
            new_name='interests',
        ),
    ]
