export const GET_USER_TASKS = "GET_USER_TASKS";
export const STORE_USER_TASKS = "STORE_USER_TASKS";
export const GET_TASK_ANALYTICS = "GET_TASK_ANALYTICS";
export const STORE_TASK_ANALYTICS = "STORE_TASK_ANALYTICS";